### ISSUE TITLE
Buying/selling with a resting order should take a pivot as `restingOrder` params

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove.js#774]
**Describe the bug**
When executing a `buy` order at price `p` there is currently no way to provide a pivot in case a resting `bid` order is inserted on Mangrove. Therefore the backend is currently using best as pivot. This is bad since `p` may not be the best bid.
A solution is to evaluate the pivot for a bid a price `p` and pass that pivot to the `take` call to `MangroveOrder`. This thus also requires a modification of the backend to take that pivot instead of best.

Similar solution for the `sell` order at price `p` where one has to compute the best pivot for an ask at price `p`.

**Comment by espendk** [comment]
Expanding a bit, this is an issue when none of the order is executed immediately. 

Because in the case where part of the order is executed immediately, the remainder should be posted at the best price since otherwise either

1. more of the order should have been executed or
2. the market is crossed (which it shouldn’t be for long in a functioning market).

**Comment by peterMangrove** [comment]
A comment for this can be found in `Trade` for `mangroveOrder`

**Comment by lnist** [comment]
Closing as pivots are no longer relevant.
